# Generated by Django 3.2.8 on 2021-10-30 17:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_auto_20211030_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Progects',
            new_name='Projects',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='user',
        ),
    ]
